const $=id=>document.getElementById(id);const list=$('absenceList');
for(let i=1;i<=5;i++){list.insertAdjacentHTML('beforeend',`<div class="absence-card"><h3>කොටස ${String(i).padStart(2,'0')}</h3><div class="datetime-grid"><label>පටන් ගත් දිනය<input id="a${i}StartDate" type="date"></label><label>වේලාව<input id="a${i}StartTime" type="time"></label><label>නැවත සේවයට පැමිණි දිනය<input id="a${i}EndDate" type="date"></label><label>වේලාව<input id="a${i}EndTime" type="time"></label></div></div>`)}
const dt=(d,t)=>d?(new Date(`${d}T${t||'00:00'}`)):null;
function durationParts(ms){let h=Math.max(0,Math.floor(ms/3600000));let days=Math.floor(h/24);h%=24;let years=Math.floor(days/365.25);days=Math.floor(days-years*365.25);let months=Math.floor(days/30.4375);days=Math.max(0,Math.floor(days-months*30.4375));return{years,months,days,hours:h,ms};}
function addYears(date,n){let d=new Date(date);d.setFullYear(d.getFullYear()+n);return d}
function fmt(d){return d?d.toLocaleDateString('si-LK',{year:'numeric',month:'2-digit',day:'2-digit'}):'-'}
function calculate(){const join=$('joinDate').value;if(!join){alert('කරුණාකර බැඳුණු දිනය ඇතුළත් කරන්න.');return}const now=new Date();const start=new Date(`${join}T00:00`);let totalAbs=0,rows=[];for(let i=1;i<=5;i++){const s=dt($(`a${i}StartDate`).value,$(`a${i}StartTime`).value),e=dt($(`a${i}EndDate`).value,$(`a${i}EndTime`).value);if(s&&e&&e>s){const ms=e-s;totalAbs+=ms;const p=durationParts(ms);rows.push({i,s,e,p})}else if(s||e){alert(`කොටස ${i} සඳහා දිනය/වේලාව නිවැරදිව ඇතුළත් කරන්න.`);return}}
const serviceMs=Math.max(0,now-start-totalAbs);const sp=durationParts(serviceMs);['currentYears','resultCurrentYears'].forEach(x=>$(x).textContent=sp.years);['currentMonths','resultCurrentMonths'].forEach(x=>$(x).textContent=sp.months);['currentDays','resultCurrentDays'].forEach(x=>$(x).textContent=sp.days);const ap=durationParts(totalAbs);$('absenceYears').textContent=ap.years;$('absenceMonths').textContent=ap.months;$('absenceDays').textContent=ap.days;$('absenceHours').textContent=ap.hours;$('absenceTotalText').textContent=`${ap.years} අවුරුදු ${ap.months} මාස ${ap.days} දින ${ap.hours} පැය`;
$('periodResults').innerHTML=rows.map(r=>`<div class="period-row"><b>කොටස ${String(r.i).padStart(2,'0')}</b> — ${r.p.years} අවුරුදු ${r.p.months} මාස ${r.p.days} දින ${r.p.hours} පැය</div>`).join('');
const milestones=[12,15,22].map(n=>{let target=addYears(start,n);target=new Date(target.getTime()+totalAbs);return target});['result12Date','result15Date','result22Date'].forEach((id,i)=>$(id).textContent=fmt(milestones[i]));$('pdfJoinDate').textContent=fmt(start);$('pdfCurrentService').textContent=`${sp.years} අවුරුදු ${sp.months} මාස ${sp.days} දින`;$('pdfAbsenceDuration').textContent=`${ap.years} අවුරුදු ${ap.months} මාස ${ap.days} දින ${ap.hours} පැය`;$('pdf12Date').textContent=fmt(milestones[0]);$('pdf15Date').textContent=fmt(milestones[1]);$('pdf22Date').textContent=fmt(milestones[2]);$('pdfGenerated').textContent=fmt(now);$('pdfPeriods').querySelector('tbody').innerHTML=rows.map(r=>`<tr><td>කොටස ${String(r.i).padStart(2,'0')}</td><td>${r.s.toLocaleString('si-LK')}</td><td>${r.e.toLocaleString('si-LK')}</td><td>${r.p.years} අවුරුදු ${r.p.months} මාස ${r.p.days} දින ${r.p.hours} පැය</td></tr>`).join('');window._calc={sp,ap,rows};}
$('calculateBtn').onclick=calculate;$('resetBtn').onclick=()=>location.reload();$('printBtn').onclick=()=>{calculate();window.print()};$('pdfBtn').onclick=()=>{calculate();const el=$('pdfContent');el.style.display='block';if(typeof html2pdf==='function')html2pdf().set({margin:8,filename:'Military-Sudda-Kala-Gananaya.pdf',html2canvas:{scale:1},jsPDF:{unit:'mm',format:'a4'}}).from(el).save().finally(()=>el.style.display='none');else alert('PDF library එක ලබාගත නොහැක. Internet connection එක පරීක්ෂා කරන්න.')};
